services:
    worker:
        build:
            context: .
            target: dev
        env_file: .env
        volumes:
            - .:/workspace
            - venv:/workspace/.venv
        depends_on:
            postgres:
                condition: service_healthy
            broker:
                condition: service_healthy
        networks:
            - backend
        restart: unless-stopped

volumes:
    venv:
