
services:
    api:
        build:
            context: .
            target: dev
        env_file: .env
        volumes:
            - .:/workspace
            - vendor:/workspace/vendor
            - ../packages:/packages
        ports:
            - "8080:9000"
        depends_on:
            postgres:
                condition: service_healthy
            broker:
                condition: service_healthy
        networks:
            - frontend
            - backend
        restart: unless-stopped

volumes:
    vendor: