
services:
    api:
        build:
            context: ./services/api
            target: dev
        env_file: .env
        volumes:
            - ./services/api:/var/www/html
            - vendor:/var/www/html/vendor
        ports:
            - "8080:9000"
        depends_on:
            postgres:
                condition: service_healthy
            broker:
                condition: service_healthy
        networks:
            - frontend
            - backend
        restart: unless-stopped

volumes:
    vendor: